# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title An Rcpp function for Exercise 9.8 (page 278, Statistical Computing with R).
#' @description An Rcpp function for Exercise 9.8 (page 278, Statistical Computing with R).
#' @param a A parameter the bivariate density.
#' @param b A parameter the bivariate density.
#' @param n A parameter the bivariate density.
#' @param M Length of the chain.
#' @return A chain.
#' @export
CppFun <- function(a, b, n, M) {
    .Call('_StatComp21078_CppFun', PACKAGE = 'StatComp21078', a, b, n, M)
}

